#frozen_string_liternal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'twitter-typeahead-rails'
gem 'devise'
gem 'ancestry'
gem 'activestorage', '~> 6.0', '>= 6.0.2.2'
gem 'bootstrap-sass', '~> 3.4.1'
gem 'coffee-rails', '~> 5.0'
gem 'faker', git: 'https://github.com/faker-ruby/faker.git', branch: 'master'
gem 'jbuilder', github: 'rails/jbuilder', branch: 'master'
# gem 'jquery-rails'
gem 'oj'
gem 'oj_mimic_json'
gem 'pq'
gem 'puma', '~> 3.11'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'
gem 'sassc-rails', '>= 2.1.0'
gem 'simple_form'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'bootsnap', '~> 1.4', '>= 1.4.6'
gem 'factory_bot'
gem 'webpacker', '~> 4.0' 
gem 'meta-tags'
gem 'breadcrumbs_on_rails'
gem 'ransack'
gem 'pundit'
gem 'doorkeeper'
gem 'responders'
gem 'active_model_serializers'
gem 'jquery-turbolinks'
gem 'railties', '~> 6.0', '>= 6.0.2.1'
gem 'omniauth'
gem 'omniauth-facebook'


group :development, :test do
  gem 'factory_bot'
  gem 'faker', git: 'https://github.com/faker-ruby/faker.git', branch: 'master'
  gem 'database_cleaner'
  gem 'pry'
  gem 'pg', '~> 1.1'
  gem 'rails-controller-testing'
  gem 'rb-readline'
  gem 'rspec-json_expectations'
  gem 'rspec-core', '~> 3.4', '>= 3.4.4'
  gem 'rspec-mocks', '~> 3.9', '>= 3.9.1'
  gem "rspec-rails", "4.0.0.beta2"
  gem 'rspec-support', '~> 3.9', '>= 3.9.2'
end

group :development do
  gem 'listen'
  gem 'web-console', '>= 3.3.0'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara'
  gem 'db-query-matchers'
  gem 'json_spec'
  gem 'launchy'
  gem 'rubocop', require: false
  gem 'shoulda-matchers'
  gem 'webdrivers'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

